### PR TITLE
Added export_caffe_model

### PR DESCRIPTION
**Pull request by zoharby**
Added a conversion script to export MatConvNet models to Caffe.

Created instead of PR #298 on the devel branch.

### CODE REVIEW

**Comment by lenck** [comment]
Hi, sorry that it is still hanging here. I've been polishing the code a bit and now I'm waiting for Andrea to accept it. So hopefully it would get to the devel branch soon...

**Comment by zoharby** [comment]
No rush :)
Thanks!

**Comment by lenck** [comment]
Hmm, sorry that it got stuck so much. I've just pushed the changes I've done to a new branch `simplenn-caffe-deploy`. You can see them e.g. here: https://github.com/vlfeat/matconvnet/compare/simplenn-caffe-deploy

**Comment by zoharby** [comment]
Great work!
Thanks for the update.

**Comment by zoharby** [comment]
Hey, any updates regarding merging this to master?

**Comment by lenck** [comment]
Hey, just merged it to devel...
Sorry, I was thinking about extending it for exporting dagnn models too, but didn't have time at the end...

But, for some reason, github didn't detect the merge. But you are credited in the authorship of the script, so I hope it's ok that I close this pull request...

**Comment by zoharby** [comment]
Thanks, that's great

**Pull request closed without merging**
